Cloud storage
ynigoreyes/resume-engine pull request #12
Opened 2019-03-08 06:16 UTC by ynigoreyes

I have it set up to automatically look for resume_1->4 on GCloudStorage using tags and `_blank` targets. I remember you telling me this haha. Good call

2019-03-08 06:21 UTC, ynigoreyes commented
Don't worry most of the changes are in yarn.lock lol

2019-03-09 07:13 UTC, swoldemi requested changes
May want to explain how to connect to the Cloud SQL instance using MySQL Workbench (i.e. create new connection, leave default IP and port, paste root password, click schemas tab to view tables, etc). Worked fine for me though!

2019-03-09 07:13 UTC, swoldemi commented on README.md
> +	4. Make sure that you do not have any process running on port 3306 by running `lsof -i tcp:3306`
Windows equivalent for item 4: `netstat -ano -p tcp` .

2019-03-09 07:14 UTC, swoldemi commented
Looks good (or at least I think so since a lot of the changes are React additions lol 👀). I was able to connect to the instance using the Cloud SQL Proxy and MySQL Workbench in less than 5 minutes. Requested 1 change in the README.

2019-03-09 15:37 UTC, merged